### ISSUE TITLE
Document jextract, in the tools section

### ISSUE THREAD

**Issue by smithwil** [eclipse/openj9-docs#268] opened 2019-05-15 11:13 UTC
The jextract tool still has a purpose: it collects a system dump, all the shared libraries (DLLs) that were loaded by the java process in the dump and the TraceFormat .dat files, and puts them into a zip file. This zip is often requested by support teams, so they can debug the system dump. The shared libraries (DLLs) help a debugger to format the stack traces captured in the system dump. It would be helpful if the jextract tool could be documented so that support teams can point users at the document, when asking for a system dump.

**Comment by doveye** [comment] 2019-06-10 12:24
I just installed the latest v8 (Windows) from https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9, and jextract does not appear to be in it. @pshipton - should it be there?

**Comment by pshipton** [comment] 2019-06-10 13:09
Correct, it is not present in Windows builds, but it is not needed on this platform. I find it present in all Linux and AIX builds.

**Comment by pshipton** [comment] 2019-06-10 13:12
@DanHeidinga is jextract required for macOS?

**Comment by DanHeidinga** [comment] 2019-06-10 13:35
jextract is present in OSX builds similar to Linux and AIX.  I haven't confirmed that it's required but given the similar *nix heritage, I'd be surprised if it wasn't.

**Comment by doveye** [comment] 2019-06-10 14:05
Thanks for the confirmations :)

**Comment by pshipton** [comment] 2019-06-10 23:02
@DanHeidinga I checked a build from Adopt, and I don't see jextract included. Are you seeing something different, or checking a different type of build?

https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#x64_mac

**Comment by DanHeidinga** [comment] 2019-06-11 01:23
I checked my local jdk11 build.  Let me confirm with an Adopt build

**Comment by DanHeidinga** [comment] 2019-06-11 03:26
Adopt jdk11 mac build has `jextract`:
```
$ jdk-11.0.3+7/Contents/Home/bin/jextract -J-version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.3, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190531_242 (JIT enabled, AOT enabled)
OpenJ9   - b8ab01656
OMR      - b56045d2
JCL      - dcdc97f9dc based on jdk-11.0.3+7)
```

**Comment by pshipton** [comment] 2019-06-11 03:50
@DanHeidinga Please check jdk8 as well, it is what I looked at and could not find jextract in this build.

**Comment by DanHeidinga** [comment] 2019-06-11 12:55
`jextract` is not present on Adopt JDK8 mac builds

**Comment by doveye** [comment] 2019-06-12 10:10
The jextract topic is back in the draft content, see https://eclipse.github.io/openj9-docs-staging/291/tool_jextract/.
@DanHeidinga  @pshipton   I've added icons to indicate that this topic applies to macos from Java 11 (I assume it will be in later releases). One other question - in some of our other (original) doc, we say the output of jextract is saved to the current directory. I had a go at running it on my Linux virtual box and it went to the directory that contained the core file instead. Do you know if the latter behaviour is correct (and if it's the same on all releases/operating systems)?
@smithwil, if you think any other info would be useful to add to the topic, please let me know.

**Comment by pshipton** [comment] 2019-06-14 18:33
> `jextract` is not present on Adopt JDK8 mac builds 

@DanHeidinga the original question was, does macOS need `jextract` for debugging, to copy the system libaries. Or are they already included in the core file? If needed, jdk8 needs to be updated to include `jextract`, otherwise it can be removed from jdk11 and doesn't need to be documented.

**Comment by pshipton** [comment] 2019-06-14 18:34
@doveye I don't believe `jextract` has changed behavior in years. We should document however it works.

**Comment by doveye** [comment] 2019-06-17 13:28
@pshipton Ok, I was hoping someone could confirm how it works as the doc doesn't match my test. But I've tried it on Windows now (via an IBM SDK) and that also outputs to the directory that contains the dump file, so I'm going to assume that is what happens on all operating systems, and will add that info to the doc.

**Comment by doveye** [comment] 2019-06-19 10:09
The updates are now in the current docs (https://eclipse.github.io/openj9-docs/tool_jextract/), so this issue should be closed. However, Peter's question of what is required on macos is still outstanding (@DanHeidinga), so I'll leave this issue open until that question is answered, then another issue can be raised to address whatever might required at that point.

> [...] does macOS need jextract for debugging, to copy the system libaries. Or are they already included in the core file? If needed, jdk8 needs to be updated to include jextract, otherwise it can be removed from jdk11 and doesn't need to be documented.

**Comment by SueChaplain** [comment] 2019-09-23 13:34
@DanHeidinga - just doing some housekeeping and this one is still open. Is there some work to do for macOS please? ^^^^

**Comment by ed03875** [comment] 2019-09-23 15:14
I have to start somewhere because I simply don't understand this previous post pertaining to J8 : "Correct, (jextract) it is not present in Windows builds, but it is not needed on this platform. I find it present in all Linux and AIX builds. "  I don't see how it is not needed.  How is one suppose to extract a java core from a full process dump without jextract ?

**Comment by doveye** [comment] 2019-09-23 15:23
@ed03875, hopefully the doc explains it :)  https://www.eclipse.org/openj9/docs/tool_jextract/

**Comment by ed03875** [comment] 2019-09-23 17:50
So I am writing this on behalf of a number of us confused people.  We are running the JVM from our process  we have always used jextract and then  jdmpview to get at the java core when a separate core is not found on the target machine. .  We assume that windbg knows nothing about java cores so how do we obtain the javacore that has always been available to us using the steps above ??  There are no separate cores on the machine where the problem occurs.

**Comment by DanHeidinga** [comment] 2019-09-23 19:52
> @DanHeidinga - just doing some housekeeping and this one is still open. Is there some work to do for macOS please? ^^^^

Based on a quick look at osx core files, there's more work to do - opened https://github.com/eclipse/openj9/issues/7197 to track adding jextract to osx jdk8

**Comment by pshipton** [comment] 2019-09-23 20:59
@ed03875 what version of Java are you using? Assuming Java 8 or later (and some earlier versions of IBM Java), jextract just zips up existing files, it doesn't add anything or create anything that isn't already on the file system. 

If you are using jdmpview to open the zip file produced by jextract, the equivalent is to run jdmpview directly on the process core file you specified when running jextract. The jextract step is not needed to run jdmpview.

If you still have questions, please provide an example of the steps you are running.

**Comment by ed03875** [comment] 2019-09-24 15:12
Thanks for your response, I am using Java 8.  I had found that I could use 
jdmpview directly with -core and have moved past that .
Thanks again
Ed

**Comment by pshipton** [comment] 2019-10-22 21:01
As per https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/339, jextract is now included in Mac builds.

**Closed** 2019-10-24 11:34 UTC
