### ISSUE TITLE
Adding Mac platform support to the user docs

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9-docs#82] opened 2018-09-10 17:01 UTC
**Work at OpenJ9 to port to Mac:**

@DanHeidinga We need to plan any changes to the user documentation that are required for the Mac port at OpenJ9. 

- update to the support topic, including platform support and build environment
- across the doc we mention differences per platform. What differences will exist for Mac? 
    - supported options
    - supported GC policies
    - any limitations etc

As the work progresses, perhaps the team can add any relevant notes here please?

**Comment by SueChaplain** [comment] 2018-11-07 15:52
[macos.xlsx](https://github.com/eclipse/openj9-docs/files/2558114/macos.xlsx)
@DanHeidinga - please can you get someone to go through this spreadsheet and provide the input for macOS?

**Comment by SueChaplain** [comment] 2018-12-04 09:38
@babsingh - is this something you can help with please? The user docs have very little information about macOS and users will want to understand which options are supported / which GC policies etc.

**Comment by babsingh** [comment] 2018-12-04 21:49
Majority of Linux documentation should be applicable to MacOS. There are few outliers. As a starting point, we can replicate Linux x86 documentation for OSX.

Answering doubts raised within [macos.xlsx](https://github.com/eclipse/openj9-docs/files/2558114/macos.xlsx):
1. **[GC]** Currently, GC policy `metronome` is not supported on OSX. It might be enabled on OSX if they can support high-resolution clock. All other GC policies supported on Linux should be available on OSX. @dmitripivkine can you confirm this?

2. **[GC]** [-Xconcurrentbackground](https://www.eclipse.org/openj9/docs/xconcurrentbackground/) is set to **1** by default on OSX. @dmitripivkine can you confirm this?

3. **[JIT]** @0xdaryl @nbhuiyan Is [-Xjit/-Xnojit](https://www.eclipse.org/openj9/docs/xjit/) documentation valid for OSX? Is it identical to Linux x86?

4. **[JIT/VM]** [-Xlp](https://www.eclipse.org/openj9/docs/xlp/), [-Xlp:codecache](https://www.eclipse.org/openj9/docs/xlpcodecache/), [-Xlp:objectheap](https://www.eclipse.org/openj9/docs/xlpobjectheap/) behavior on OSX and Linux x86 should be the same. @0xdaryl @nbhuiyan @pshipton do you agree?

5. **[VM]** [-Dcom.ibm.tools.attach.enable=[yes|no]](https://www.eclipse.org/openj9/docs/dcomibmtoolsattachenable) is enabled by default on OSX similar to Linux.

6. **[VM]** [-Xtrace](https://www.eclipse.org/openj9/docs/xtrace/) behavior on OSX and Linux should be the same.

7. **[VM]** [-Xdump](https://www.eclipse.org/openj9/docs/xdump/) behavior on OSX and Linux should be the same. Currently, `jdmpview` is unavailable on OSX. So, core dumps generated by `-Xdump` can't be viewed on OSX. @mikezhang1234567890 predicts `jdmpview` support to be available by Jan 2019.

8. **[VM]** [-Xrs:sync](https://www.eclipse.org/openj9/docs/xrs/) behavior on OSX should be similar to behavior on other Unix platforms: `Disables signal handling in the VM for SIGSEGV, SIGFPE, SIGBUS, SIGILL, SIGTRAP, and SIGABRT signals. However, the VM still handles the SIGQUIT and SIGTERM signals, among others`.

9. **[VM]** [-Xshareclasses](https://www.eclipse.org/openj9/docs/xshareclasses/) behavior on OSX is identical to Linux x86. @hangshao0 can you confirm this?

10. **[VM]** For [-Xthr](https://www.eclipse.org/openj9/docs/xthr/), `cfsYield | noCfsYield` should be disabled on OSX. Currently, these options are enabled on OSX. Created https://github.com/eclipse/openj9/pull/3921 and https://github.com/eclipse/omr/pull/3283 to disable CFS support on OSX. All other [-Xthr](https://www.eclipse.org/openj9/docs/xthr/) options should work on OSX.

11. https://www.eclipse.org/openj9/docs/openj9_defaults/ [Second table]. OSX behavior should be similar to Linux x86. @pshipton do you agree?

12. https://www.eclipse.org/openj9/docs/openj9_directories/ [First table]. OSX Java 8 - `<install_dir>/jre/lib/default`. OSX Java 11 - `<install_dir>/lib/default`. Unlike Linux SDKs, OSX SDKs don't have `<arch>` directory.

13. https://www.eclipse.org/openj9/docs/messages_intro/#finding-aix-messages. On Linux, messages are logged by the `syslog daemon`. On OSX, `syslog` is also available. But, [Apple broke syslog on Sierra and High Sierra](https://stackoverflow.com/questions/49805750/macos-high-sierra-syslog-does-not-work). On OSX, `Console.app` may be used if `syslog - /var/log/system.log` is unavailable. @DanHeidinga can you verify this?

14. https://www.eclipse.org/openj9/docs/env_var/. OSX behavior should be similar to Linux.

**Comment by pshipton** [comment] 2018-12-04 21:58
Re -Xlp how are large pages enabled on MacOS? What large pages are available when running -verbose:sizes?

**Comment by pshipton** [comment] 2018-12-04 22:01
Re https://www.eclipse.org/openj9/docs/openj9_defaults/ please confirm via providing the -verbose:sizes output.

**Comment by hangshao0** [comment] 2018-12-04 22:03
> [VM] -Xshareclasses behavior on OSX is identical to Linux x86. @hangshao0 can you confirm this?

Shared class is enabled by default on Java 11 on all platforms except OSX.
Once https://github.com/eclipse/openj9/pull/3858 is merged. Shared class will be enabled by default on Java 8 on all platforms except OSX

**Comment by babsingh** [comment] 2018-12-04 22:09
`-verbose:sizes` output on OSX:

```
Java 8:
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx128M       maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox510M       maximum old space size
  -Xmx512M        memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size


Java 11:
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx1G         maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox4094M      maximum old space size
  -Xmx4G          memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
```

For ` -Xlp:objectheap|codecache`, only 4K is available for large page size.

**Comment by babsingh** [comment] 2018-12-04 22:11
@hangshao0 are all cmdline options listed in [-Xshareclasses](https://www.eclipse.org/openj9/docs/xshareclasses/) available on OSX?

**Comment by dmitripivkine** [comment] 2018-12-04 22:30
> 1. **[GC]** Currently, GC policy `metronome` is not supported on OSX. It might be enabled on OSX if they can support high-resolution clock. All other GC policies supported on Linux should be available on OSX. @dmitripivkine can you confirm this?

This is correct. Currently `-Xgcpolicy:metronome` is supported on xLinux and AIX only. Also Concurrent Scavenger `-Xgc:concurrentScavenge` is supported on xLinux but is not on OSX (can be supported in future) 

> 2. **[GC]** [-Xconcurrentbackground](https://www.eclipse.org/openj9/docs/xconcurrentbackground/) is set to **1** by default on OSX. @dmitripivkine can you confirm this?

This is correct. The default value for `-Xconcurrentbackground` is set to 1 for all platforms excluding zLinux

**Comment by dmitripivkine** [comment] 2018-12-04 22:34
`-Xlp` behaviour is not the same as far as we have support for 4K pages only (xLinux supports Huge pages)

**Comment by babsingh** [comment] 2018-12-06 19:11
I will update the spread sheet once the JIT team responds to the below question:

[JIT] @0xdaryl @nbhuiyan Is -Xjit/-Xnojit documentation (https://www.eclipse.org/openj9/docs/xjit/) valid for OSX? Are there any special cases for Xjit/-Xnojit on OSX?

@SueChaplain in the spreadsheet, should i assume **yes** for empty slots in the **macOS column C** with no doubts? do we need to verify all options in the spreadsheet?

**Comment by nbhuiyan** [comment] 2018-12-10 17:11
@babsingh `-Xjit` and `-Xnojit` works on macOS the same way it does on Linux on x86-64. So far, I have not come across any case of a parameter working on x86-64 Linux and not on macOS.

**Comment by babsingh** [comment] 2018-12-11 00:01
@SueChaplain would you like me to verify all options in the spreadsheet or just the ones with a doubt associated?

**Comment by SueChaplain** [comment] 2018-12-11 09:25
@babsingh - please can you run your eye over all of them? I made some assumptions about ones that probably didn't apply or might have some differences but I'm not really best placed to do that.

**Comment by SueChaplain** [comment] 2019-01-03 13:17
Hi @babsingh - how is this work progressing please? I'm just back from the Christmas break and wondering if we can handle this work in our first iteration this year. Thanks!

**Comment by babsingh** [comment] 2019-01-03 14:19
@SueChaplain before vacation, i had reviewed half of the list. i still have to review the remaining half of the list. when is the first iteration due?

**Comment by babsingh** [comment] 2019-01-03 14:34
@SueChaplain i will provide a first draft tomorrow.

**Comment by babsingh** [comment] 2019-01-04 21:09
**Updated excel:** [macos-babneet.xlsx](https://github.com/eclipse/openj9-docs/files/2728431/macos-babneet.xlsx). I have filled column C (**macOS? yes/no**). I have used column D and F for questions/notes. Added Column E; it contains a link to the online documentation for each option.

Questions for @DanHeidinga or @pshipton -
1. [-Xcheck:dump](https://www.eclipse.org/openj9/docs/xcheck/#dump) doesn't work on OSX because function `J9RASCheckDump` is unimplemented for OSX in OpenJ9. [-Xcheck:dump](https://www.eclipse.org/openj9/docs/xcheck/#dump) seems relevant for OSX. Do you guys agree? If so, I will open an OpenJ9 issue to add OSX support for `-Xcheck:dump`.
2. Should [-Xnuma:none](https://www.eclipse.org/openj9/docs/xnumanone/) and [-XX:[+|-]InterleaveMemory](https://www.eclipse.org/openj9/docs/xxinterleavememory/) be disabled on OSX due to absence of NUMA support? 
   - OSX doesn't have NUMA support: https://news.ycombinator.com/item?id=9500592. 
   - Instead, OSX has a   thread affinity API:   https://developer.apple.com/library/archive/releasenotes/Performance/RN-AffinityAPI.   
   - On Mac Pros with Xeon processors, QPI, Intel's implementation of NUMA, takes   place fully within the processor just as HyperTransport is AMDs.
3.  Should [-XX:[+|-]IdleTuningCompactOnIdle](https://www.eclipse.org/openj9/docs/xxidletuningcompactonidle), [-XX:[+|-]IdleTuningGcOnIdle](https://www.eclipse.org/openj9/docs/xxidletuninggconidle),[-XX:IdleTuningMinFreeHeapOnIdle](https://www.eclipse.org/openj9/docs/xxidletuningminfreeheaponidle) and [-XX:IdleTuningMinIdleWaitTime](https://www.eclipse.org/openj9/docs/xxidletuningminidlewaittime) be supported on OSX? The first three options are used by the GC and enabled by the `J9VM_GC_IDLE_HEAP_MANAGER` flag. `J9VM_GC_IDLE_HEAP_MANAGER` is enabled on OSX since Linux spec files were used to create OSX spec files. The fourth option is always enabled, used by the JIT and related to the first three options. The online doc says that the four options are only supported on Linux. After looking at the code, all four options should work on OSX. I am not sure if we want to support these options on OSX.
4. Currently, [-Xthr:cfsYield | noCfsYield](https://www.eclipse.org/openj9/docs/xthr/#cfsyield-nocfsyield-linux-only) is enabled on OSX. Since OSX doesn't have a Completely Fair Scheduler, this feature should be disabled on OSX. Created https://github.com/eclipse/openj9/pull/3921 to disable [-Xthr:cfsYield | noCfsYield](https://www.eclipse.org/openj9/docs/xthr/#cfsyield-nocfsyield-linux-only) on OSX.
5. [-XtlhPrefetch](https://www.eclipse.org/openj9/docs/xtlhprefetch) is only supported on AIX and Windows. But, [-XtlhPrefetch](https://www.eclipse.org/openj9/docs/xtlhprefetch) gets accepted as cmdline option on Linux, OSX and other platforms. Should [-XtlhPrefetch](https://www.eclipse.org/openj9/docs/xtlhprefetch) be unrecognized on unsupported platforms?
6. In the documentation of [-Xtrace](https://www.eclipse.org/openj9/docs/xtrace/#tracepoint-specification), there is a reference to **ibm_gpu** component, which represents class library graphics processing unit (GPU) native code (supported on Linux only). I am guessing **ibm_gpu** component won't be supported on OSX. Can you confirm this?
7. Other than NLS messages, I couldn't find the source code or history related to [-Xrdbginfo](https://www.eclipse.org/openj9/docs/xrdbginfo/) in OpenJ9. What happens to the documentation of [-Xrdbginfo](https://www.eclipse.org/openj9/docs/xrdbginfo/)? Do we remove it or do we keep it with a note?
8. For [-Xshareclasses](https://www.eclipse.org/openj9/docs/xshareclasses/), I have assumed that the Linux content applies to OSX. Is this assumption correct? Also, I have proposed that "an OSX user may need to set, kern.sysv.shmmax and kern.sysv.shmall, for shared classes to work".
9. In the [-Xdump](https://www.eclipse.org/openj9/docs/xdump/#system-dumps-on-linux) documentation, there is a section named **System dumps on Linux** at the end. Should we add a section for **System dumps on OSX** since system dumps may not generate by default on OSX?

**Comment by SueChaplain** [comment] 2019-01-07 15:42
Whilst working through the list I have the following additional questions:

- On OS X, what is the equivalent variable for LIBPATH (AIX) and LD_LIBRARY_PATH (Linux)
- Please confirm `ulimits` also apply on OS X and might need increasing under similar circumstances to AIX/Linux.

**Comment by pshipton** [comment] 2019-01-07 16:16
1. Agree
2. What do you mean by "disabled"? The options can still be parsed. i.e. z/OS recognizes -Xnuma:none
3. We should not claim support for these options on MacOS until such time as they have been confirmed working. Based on some softmx test results, I'm not sure madvise(..., MADV_DONTNEED) gives the same behavior as Linux.
4. Ok.
5. Accepting the option on unsupported platforms is fine.
6. I believe the ibm_gpu trace component is obsolete on all platforms, the code was re-written before OpenJ9 was created. GPU may be supported on macOS in the future, but an NVIDIA gpu is required, which I don't believe is common occurrence. 
7. -Xrdbginfo is obsolete and should be removed from the doc
8. Yes, -Xshareclasses support is the same a Linux. Setting  kern.sysv.shmmax and kern.sysv.shmall is only required to use the nonpersistent -Xshareclasses option, which is not the default.
9. Makes sense to describe any special behavior on MacOS.

**Comment by babsingh** [comment] 2019-01-07 17:31
fyi - @pshipton 

> What do you mean by "disabled"? The options can still be parsed. i.e. z/OS recognizes -Xnuma:none

"disabled": should options [-Xnuma:none](https://www.eclipse.org/openj9/docs/xnumanone/) and [-XX:[+|-]InterleaveMemory](https://www.eclipse.org/openj9/docs/xxinterleavememory/) be unrecognized since they are unsupported on OSX? Based upon prior answers, accepting the options on unsupported platforms is fine. But, we should not claim support in the documentation until the options are confirmed to be working.

fyi - @SueChaplain 

> On OS X, what is the equivalent variable for LIBPATH (AIX) and LD_LIBRARY_PATH (Linux)

The equivalent variable is `DYLD_LIBRARY_PATH`: https://github.com/eclipse/openj9/pull/3765.

> Please confirm ulimits also apply on OS X and might need increasing under similar circumstances to AIX/Linux.

On OSX, resource limits are set using `launchctl`, `ulimit`, and `kern.<VARIABLES>`. Also, instructions on setting resource limits vary depending upon OSX version:
1) [open-files-limit/#mac-os-x-el-capitan](https://docs.basho.com/riak/kv/2.0.8/using/performance/open-files-limit/#mac-os-x-el-capitan)
2) [open-files-limit/#mac-os-x-yosemite](https://docs.basho.com/riak/kv/2.0.8/using/performance/open-files-limit/#mac-os-x-yosemite)
3) [open-files-limit/#mac-os-x-older-versions](https://docs.basho.com/riak/kv/2.0.8/using/performance/open-files-limit/#mac-os-x-older-versions)

**Closed** 2019-01-14 11:55 UTC
Labels: enhancement
